### ISSUE TITLE
Consider using user IDs instead of usernames for the database

### ISSUE THREAD

**Issue by 0xallie** [bethylamine/soupcan#27]
I know existing entries can't be automatically migrated because they're hashed, but it may be worth storing user IDs instead of usernames going forward to avoid labels disappearing because of a username change.

**Comment by bethylamine** [comment]
I do record IDs internally where possible, which relies on the API but the Twitter website doesn't have user IDs available so reports can't be made based on ID.

**Comment by bethylamine** [comment]
![image](https://user-images.githubusercontent.com/130214958/236647310-ac3278c1-472c-4abc-bca3-28e0ebf93150.png)

Example.

**Comment by bethylamine** [comment]
Unfortunately since the client doesn't have access to user IDs, the database it uses still has to be based on screen names. Unless there is a better solution available

**Comment by bethylamine** [comment]
![image](https://user-images.githubusercontent.com/130214958/236647381-390af783-a2ce-4166-8562-187f6c6aaa00.png)

There are only a handful of cases where the ID wasn't able to be fetched, and it doesn't seem like it was based on API restrictions. I must have been grandfathered in or something because I'm not paying for this API access.

**Comment by bethylamine** [comment]
Closing as wontfix
