### ISSUE TITLE
Suggestion: Autoblock Marked users

### ISSUE THREAD

**Issue by Ashly9243** [bethylamine/soupcan#45]
A feature I would enjoy is a feature that auto blocks marked users similar to how [Blue Blocker](https://github.com/kheina-com/Blue-Blocker) does it

**Comment by bethylamine** [comment]
I see the value here, that is,

* Known transphobes are removed from your Twitter experience before needing to interact with them, which removes the number of spoons needed to navigate Twitter.
* Preventing abuse from transphobes, by pre-emptively preventing access to easily targeted harassment / pile-ons to your account
* It's a one-click, if nuclear, solution to removing a lot of transphobia from your view of Twitter.


On the other hand, I'm hesitant to implement this because:

* I'm not sure I feel good about putting user boundaries in the hands of my plugin. I would feel somewhat responsible for facilitating the creation of 'bubbles'.
* In addition to above, it leans more into essentializing transphobes rather than 'people who have said or done transphobic things'.
* A lot of transphobia right now is coming from newer/quieter accounts that are less likely to be reported yet
* There is a fine balance between auto-blocking quickly enough to be effective and not too quickly that you get locked out of your account / logged out
* There are still some false positives, but I guess the feature could also unblock if that user gets appealed.

**Comment by bethylamine** [comment]
(I have some of the same feelings towards Blue Blocker.)

**Comment by pixiekat** [comment]
@Ashly9243 If you were looking for a solution that soft blocks (i.e., hides posts with certain terms), you can use the [Twitter De-Politificator.txt](https://github.com/DandelionSprout/adfilt/blob/master/Sensitive%20lists/Twitter%20De-Politificator.txt) filter list, which has specific gender critical phrases in it (I'm not the author but I did recommend the terf phrases get added to it).
