### ISSUE TITLE
Options not saving on iOS

### ISSUE THREAD

**Issue by bethylamine** [bethylamine/soupcan#52]
On my iPhone if I change the options, they don't save (opening options against shows them all reverted back to default.)

I was trying to enable hiding ads and it wasn't working, then I realized the options weren't sticking.

**Comment by matthewberryman** [comment]
I cannot repro here, either by opening the settings page from Settings app>Safari>Extensions>Soupcan>Settings, or via refreshing the settings page.
What version of iOS are you on?
Are you using private mode in Safari?
Possible dupe of https://github.com/bethylamine/soupcan/issues/49 ?

**Comment by matthewberryman** [comment]
So I figured out one possible way to repro, but not sure it's the same as yours @bethylamine 
I installed an updated version (there was a new build yesterday my time because a change to the README.md in [the Soupcan Safari repo](https://github.com/AcrossTheCloud/Soupcan-Safari), and then today with a push to test out https://github.com/bethylamine/soupcan/pull/53), some of the settings didn't stick across the latter update. 

Note I haven't yet matched the version in the manifest.json, but the latest build number (in brackets) is now 8

**Comment by bethylamine** [comment]
I think it was a bug fixed here https://github.com/bethylamine/soupcan/commit/c68c249e337345729bf58a403d6a2605a6e2211c#diff-0058f8f28b56203f56837e43a82e408c1ed2291273b2e77ae148e32038e07436R144
