### ISSUE TITLE
The reason box when reporting should have examples (or a link to them)

### ISSUE THREAD

**Issue by kyranet** [bethylamine/soupcan#91]
The extension notifies the user of what content should be reported (by the [ToS](https://bethylamine.github.io/library/browser-extension/tos)), however, it doesn't include a guideline or similar on how reports should be written.

Currently, the reason popup shows with the following description text:

> You can provide reasoning for your report here, if you think it may help verify your report, including links to tweets, etc. Even if it's obvious please note down what you see, since people can edit their profiles/delete tweets.

However, it does not specify how should we note them:

1. Do we just copy the Tweet's content?
	1. Can we trust a reporter's word that a deleted tweet's contents weren't changed/reworded?
	2. Is it possible to download the tweet's content on the server or similar to automatically archive the content? *This runs into Twitter's API, but it protects against user tampering and it allows to submit reports more efficiently and/or validate whether or not the linked tweets exist.*
	3. Alternatively, should the tweet be summarized and/or its ToS violations highlighted?
2. The form is auto-filled with the reported Tweet (if right-clicked on a tweet), however, the ToS explicitly says that a single tweet isn't enough and can be an one-off:
	> Use discretion: take their overall account into consideration and do not report for having one bad take or belief
4. When reporting tweets, how many of them are enough for a report?
5. What density distribution should anti-trans Tweets appear on a profile to mark it as transphobic? For example:
	1. A lot of transphobic tweets/QRTs a year ago, but nearly to none at all (high to very low density).
	2. Very few transphobic tweets/QRTs for an extended period of time, but far apart.
6. Should reported tweets be separated by anything? A space? A newline? An empty newline? `---`?
7. The [moderation guidelines](https://bethylamine.github.io/library/browser-extension/mod) describes two different kinds of signals. Does every signal warrant a report? For example, do we report users who have even a single minor signal?

**Comment by CJH87** [comment]
Certainly the reports which add "context the reporter felt were necessary" are very good, but often when the reporter felt it necessary to add context they will add context without which the report would almost certainly fail (as a lone tweet), sometimes accounts have reports where the only thing a moderator can find on that account is the reported content with off network context. And verifying that context is outside the scope of the reporter's ability/time and the report just sits.


I've thought about this myself and in the end my conclusion was similar but different. I think a reporter conviction check, which could guide the moderators, could be helpful. Along a scale to the following question. "**How likely do you believe it is that this tweet (and any others you add to your report) and the account which posted it, taken as a whole, intended this tweet to be transphobic?**" The scale is detailed but not relevent here - and has only 4 levels out of 10 for when the reporter believes the transphobia was intentional.



I write the following with **zero authority**.


1. If a sole reported tweet is deleted it can still be processed as an account report (check the following, bio, look at the past day on each of the tabs).

2. The system is designed for a form of automoderation, what the reporters think (and what the moderators think of those thoughts) is more important than the content of their reports. Moderators control how much the moderation system trusts the users and as a result soupcan **knows it's users**. 

Behind the scenes the "system" is set up so that if a user is consistently in allignment with existing approved users/moderators they will acquire that status as well. When people are reported by enough approved users it doesn't matter what they actually reported because the system trusts them. 

In effect, the system teaches the soupcan database which of it's users can read and understand what is transphobia as outlined by the god empress.


3. It's pretty open format because of the above, being trusted to report accurately (on transphobia) is magnitudes more valuable than report quality. 
4. For soupcan users: use best judgement, read the guidelines. If you're wrong it doesn't matter because how often you're right or wrong is visible to moderators. For moderators: establish a clear or at least consistent __intent__. 
5. I've often reached the impression that the report box is intentionally vague because, as above, it's purpose is not to find transphobic accounts but to determine whether the soupcan user making the report is in **allignment** with the system's TOS. 



6. Read it again. The specific purpose of that prose is to demonstrate when transphobic content may not be representive of a transphobic outlook, intentional transphobia, or any account which exists for the sole intent to post transphobia.

Forgive the way I have composed this. At the start you write as though you're a moderator when asking "Can we trust a reporter's word" but then as if you're a user when you wrote "Does every signal warrant a report? For example, do we report users who have even a single minor signal?" while that particular page makes it clear what minor signals represent. 

If you're not a moderator, the stuff about minor signals is there for the purpose of identifying soupcan users that are making unhelpful reports. It doesn't mean they're reporting content that isnt transphobic or that the accounts in question are not transphobic. But it could mean they are reporting users that should not be marked.

**Comment by CJH87** [comment]
Should add, I agree that "view TOS" could be there. 

On the existing text, I think Beth has intentionally been kind on the wording to sound encouraging, as if it was to say "RTFM fool" on every time someone opened that screen people would be put off. At the end of the day some people will read the TOS, some will not, the app puts that in your face when you install. People that don't understand what to do don't acquire trust.

I have proposed in the past that the system could change what is displayed on the report dialogue only to users whose reports are consistently unsuccessful.

**Comment by bethylamine** [comment]
I will add a more guiding message plus a link to the ToS for more detail, as the reason box has evolved over time. The bare minimum is a link to the tweet, and in general the more you add, the more sure moderators can be to approve your report. Auto-approval happens without checking the reasoning, but it is now visible on people's page (with varying levels of information redacted depending on your privilege.)

**Comment by bethylamine** [comment]
![image](https://github.com/bethylamine/soupcan/assets/130214958/4e30f251-a023-4473-af7c-f65eb60647bd)

Switched to this for the time being

**Comment by bethylamine** [comment]
Tweet content is included for now, but will probably be improved further by #126 .
