### ISSUE TITLE
Inter-community drama

### ISSUE THREAD

**Issue by bethylamine** [bethylamine/soupcan#98]
Hi,

It has been an issue a couple of times where someone will say something that gets attention and get marked red in Soupcan, then I will get backlash and asked why they are marked red. This is not caused by bad actors but a few legitimate users with high trust marking the account. I'd like to open the floor for any suggestions on how this can be improved.

Requiring more votes may not stop this problem because if a number of people are aggrieved, more people will report; and transphobic accounts that attract less attention will stay unapproved for longer (if not forever.)

I can think of a view ideas, which are not mutually exclusive:
* Require that reports that don't come from moderators to only count if they were at least, say, 1 week apart. This would prevent a trigger-happy situation where one event causes a pile-on which results in reports.
* Improve the reporting guidelines to be wary and careful of situations like this where a lot of attention is garnered on an event but it doesn't make a pattern.
* Require a reason to be written in (no blank reports.) And/or require that a tweet link is included.
* Count reports that reference the same tweet as only 1 report.
* Giving users a brief popup guide on what is reportable and what isn't when they make their first report (or first report without having seen the guide)
* Adjust trust algorithm - either make it slower, or capped at tiers until they show specific exemplary reporting/appealing (reporting 100 sockpuppets is easy, but it doesn't necessarily show good judgment for on-the-fence cases)
* Requiring higher thresholds for bigger accounts?

Discussion is welcome

**Comment by CallistaAI** [comment]
The reports came from legitimate users with high trust. I believe you when you say this. This indicates to me that perhaps they should not have such trust if they use it in this way. However if that is not possible why not have a much much higher threshold for changing green marked names to red as the chances of true ideological defection are fairly low.

**Comment by bethylamine** [comment]
> The reports came from legitimate users with high trust. I believe you when you say this. This indicates to me that perhaps they should not have such trust if they use it in this way. However if that is not possible to change why not have a much much higher threshold for changing green marked names to red as the chances of true ideological defection are fairly low.

The "trust" value is only an indicator that they are using the extension properly and not much more than that. There are no green marked names in Soupcan, it is normal (everyone) and red (transphobes). There was a suggestion in #93 that some reports could be flagged as not being able to be auto-approved, in these kinds of cases

**Comment by CallistaAI** [comment]
Sorry, these were users marked green in SE. Perhaps that should be taken into account?

**Comment by bethylamine** [comment]
That could be a possibility, although it seems to potentially incentivize getting yourself marked green in Shinigami to get protection in Soupcan? Which I'm not sure I want to incentivize (dependency on another plugin) In either case it could be possible to set a higher threshold for accounts which are known in the system one way or another as non-transphobic

**Comment by bethylamine** [comment]
Added a message in the report box as something that can be immediately updated:

![image](https://github.com/bethylamine/soupcan/assets/130214958/38d02cc1-d9cf-41fa-bb56-249b2e9cd8ef)

**Comment by CallistaAI** [comment]
The replies I got from a random internet trans dude during our convo there kind of show the hostility that's out there for this kind of intracommunity issue. I am skeptical that asking people not to do the thing they did will have much of an effect. Also there's no algorithm that understands context and the core flaw of an automated trust system remains. As soupcan gains adoption the incentive to game said system increases and the internal conflicts within our community are in fact powerful enough to give people motive to try to exploit it. You will eventually be forced to place humans who understand the dynamics at play in the way of reports and adding a red marking or the system will be dominated by people trying to bend the system to their personal wills.

This problem is only going to get worse with time and you will be asked to involve the app in more and more contentious feuds within the community. I strongly advise having human reviews of markings, even if they happen after the fact as a means to self correct for this.

**Comment by hasrock36** [comment]
I think making it so each tweet only counts for one report might be a good way to reduce abuse. Requiring reports to have a link also isn't a bad idea.

**Comment by bethylamine** [comment]
Following up in #126.
